### ISSUE TITLE
General question regarding the editor

### ISSUE THREAD

**Issue by deronsizemore** [froala/django-froala-editor#1]
This editor looks really nice and I might even give it a shot at replacing TinyMCE 4 on a site. I'm wondering though, does django-froala-editor make it easy to upload images into the body field? I see that's an option in their demo, but that would be a pretty big requirement for me; easy image uploads.

**Comment by davemutton** [comment]
I've followed these instructions and I'm struggling to get image uploads working. Are there any other settings?

**Comment by deronsizemore** [comment]
@davemutton I did a lot of customization on my end to get things working how I wanted with Froala. I used the option that Froala provides for image upload url: https://editor.froala.com/options#imageUploadURL and then created my own view which handles the image upload.

**Comment by davemutton** [comment]
@deronsizemore
Am you able to.share that view? I'm not sure where to start

**Comment by deronsizemore** [comment]
@davemutton I'm actually using the django-froala app and started with their view which is here: https://github.com/froala/django-froala-editor/blob/master/froala_editor/views.py#L10

I set my imageUploadURL option for Froala to:

    imageUploadURL: "/froala/image_upload/",

I also found that I needed to pass in the csrf_token to the upload view, so I have this option for Froala also:

    imageUploadParams: {'csrfmiddlewaretoken': '{{ csrf_token }}'},

I'm initializing Froala right inside of my <form> tag so that I can pass in the csrf_token.

If it will help, here's my exact view for uploading: http://pastebin.com/h1ffPZ5V

Heavily customized as you can see, but I started with the base django-froala view from above. I customized it because I'm storing uploads to Amazon S3

Hope that helps.

**Comment by davemutton** [comment]
Thanks.. That gives me a place to start!
