### ISSUE TITLE
Options on widget can not be set dynamically

### ISSUE THREAD

**Issue by ludw** [froala/django-froala-editor#11]
We have several froala editors on the same page where we need to set the maxCharacters option dynamically for each one.

Since all the editors are on the same Model the options instance used in the model is used for each editor. This means that when we set the value dynamically all the editors get the same value.

Heres some code showing what we do:

``` python
            forms[x].fields['foo'].widget.options['maxCharacters'] = bar.maxchars
```

A workaround is to use copy on widget.options before settings the value like so:

``` python
            forms[x].fields['foo'].widget.options = copy(forms[x].fields['foo'].widget.options)
            forms[x].fields['foo'].widget.options['maxCharacters'] = bar.maxchars
```

I think it would be cleaner if that was done in django-froala-editor.

**Comment by stefanneculai** [comment]
@ludw could you please make PR? Thanks.

**Comment by akki744** [comment]
@ludw @stefanneculai This issue seems to be resolved by some recent changes. See this
https://github.com/froala/django-froala-editor/blob/master/froala_editor/widgets.py#L47
Thanks.
