### ISSUE TITLE
field.help_text does not show with widget set to froala_editor.

### ISSUE THREAD

**Issue by sabinem** [froala/django-froala-editor#13]
I have a model form: 

    class TeachersCourseProfileForm(forms.ModelForm):
         text = forms.CharField(widget=FroalaEditor)

    class Meta:
        model = CourseOwner
        fields = (... , 'text', ... )

when I display the form with widget set to Froala editor for the text field, then field.help_text comes back empty. If I remove the widget it contains the help_text that I specified in the model for that field. This seems like a bug to me. I think the models fields help_text should be preserved. This is my model:

    class CourseOwner(TimeStampedModel):
        """
        Relationship of Courses to Accounts through the Relationship of teaching.
        """
        ...
       text = models.TextField(verbose_name='Text',
                            help_text='''Personenbeschreibung: was qualifiziert Dich für das Halten dieses
                            Kurses?''',
                            blank=True)

**Comment by xtranophilist** [comment]
I think this isn't specific to FroalaEditor widget. `help_text` of  model field is preserved only when form fields are auto generated. When you are explicitly creating a form field, you are supposed to give help_text manually.

**Comment by photonauta35** [comment]
We have the same problem here... @sabinem Do you fix add a Meta verbose_name or help_text in your admin form? 

Doesnt works for us.
