### ISSUE TITLE
When I reedit a textfield certain formating such as color is gone

### ISSUE THREAD

**Issue by sabinem** [froala/django-froala-editor#14]
I do not know how to fix this. When I first format a text, everything works fine. I can add colors and tables and much more. But when I try to update and open the text in my form again, certain formating has disappeared. Can you please help me with this. The formating seems to be stored in the database, since everything shows in the Detail view, just when I reload my update form Things go wrong.

**Comment by xtranophilist** [comment]
Does the new version fix it? This looks like an issue of https://github.com/froala/wysiwyg-editor , not the django package.
