### ISSUE TITLE
what option to configure to insert html 

### ISSUE THREAD

**Issue by rjdp** [froala/django-froala-editor#17]
how to insert html

**Comment by xtranophilist** [comment]
By default, the package also includes 'Code View' plugin, which by default is available as the last button in the editor toolbar. See the screenshot below:

![screenshot from 2016-01-25 15-20-25](https://cloud.githubusercontent.com/assets/423047/12547176/ea6214aa-c376-11e5-9f40-b447cb3374ac.png)
