### ISSUE TITLE
Uncaught TypeError: $(...).froalaEditor is not a function

### ISSUE THREAD

**Issue by lip365** [froala/django-froala-editor#19]
I remember using this app in my last project without any problem but this time, I get this error on my console. I could use the app in admin page, but when I try to use it outside using {{form.media}} I get the above error. Why is this occurring and how do I fix this? Is it me doing it wrong or new version of froala?(because I used this app without any problem last time, and I loved it)

**Comment by xtranophilist** [comment]
I retested this package and as far as i could figure, i didn't find any such issue.

From the Network Tab, on Chrome DevTools, right-click on the output and select "Save as HAR with Content" and share the HAR file with us.

**Comment by lip365** [comment]
Thanks for the reply. here is the Har file, really hope this gets fixed 
[Froala.har.zip](https://github.com/froala/django-froala-editor/files/103026/Froala.har.zip)

**Comment by lip365** [comment]
![aak](https://cloud.githubusercontent.com/assets/15755683/12548091/5828ee76-c397-11e5-84bb-60aee3f410ca.png)

**Comment by xtranophilist** [comment]
I see two jQuery requests, try putting this into your settings.py file:

```FROALA_INCLUDE_JQUERY = False```

**Comment by lip365** [comment]
Still same error....any other help would be much appreciated

**Comment by lip365** [comment]
is there a way I can fix here;                 $('#id_content').froalaEditor({"fileUpload": false, "inlineMode": false, "imageUpload": false})
??

**Comment by xtranophilist** [comment]
@lip365 
Where are you including {{form.media}} ?

@stefanneculai Any idea what might be going wrong?

**Comment by lip365** [comment]
I included {{form.media}} in html file add_post.html, not post.html
