### ISSUE TITLE
License key not removing warning message

### ISSUE THREAD

**Issue by davemutton** [froala/django-froala-editor#22]
I've paid for Froala and generated a license key on the froala website.
I've inserted the key into my settings file using 
`FROALA_EDITOR_OPTIONS = {
    'KEY': 'MY_KEY_IS HERE',

}`

But I still see the message 'Unlicensed Froala editor' in admin.

**Comment by kalyanvarma** [comment]
I have opened an issue #24 regarding the same. You need to use the lowercase 'key' instead of 'KEY' for now.

**Comment by stefanneculai** [comment]
@kalyanvarma thanks for pointing that out.
