### ISSUE TITLE
How I can change the language in django admin?

### ISSUE THREAD

**Issue by studentIvan** [froala/django-froala-editor#23]
Only what I can is attach language file to Meta:

``` python
class Media:
        js = ("froala_editor/js/languages/ru.js")
```

but it will load before froala.min.js and fall to error

**Comment by CARocha** [comment]
Hi, you need put this in settings.py for change language
FROALA_EDITOR_OPTIONS = {
  'languages': 'ru',
  # other options
  # ...
}

**Comment by studentIvan** [comment]
@CARocha thank you, but so late)
