### ISSUE TITLE
Upload and use image file

### ISSUE THREAD

**Issue by bachkhoabk47** [froala/django-froala-editor#26]
Dear authors,
I've just used django-froala-editor, of course I followed your tutorial and I met problem with upload and use image file function.
From interface, I uploaded a file and approximately appeared the error: 

> something went wrong. Please try again

And then, I checked the default folder for storing data: "uploads/froala_editor/images", I can see the file that uploaded.
Also, I check the log file and see that: 

> Not Found: /admin/article/article/add/uploads/froala_editor/images/btn-login_Lp5ADiP.png/change/

So I would like to ask you about the parameter that I can set  to change the directory for load image, I mean from _**/admin/article/article/add/uploads/froala_editor/images/**_ to **_uploads/froala_editor/images_**

Second question, from TextEditor, I clicked "Insert Image" and see the button "Browse folder". I click this and see tab "Manage Image" but maybe this for server online, I could not mange it well.
So how can I change the content of the tab for suitable of my purpose.

I'm waiting for your feedback. :)

Thanks and best regards,

**Comment by pieterdd** [comment]
I'm having the same problem here. The code looks like a work in progress (some lines are commented out for example) and I can't find a view that can resolve URLs of uploaded images, so I'm not sure if it's even supported yet.

**Comment by CARocha** [comment]
Hi, i not have problem a put this in my settings.py
this code is for django 1.8.x
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_media"),
)

FROALA_EDITOR_OPTIONS = {
  'language': 'es',
  # other options
}

it's work well, 

but i still the error when browser folder -- managed image -- i don't see any my images uploads :(
any why?

thank

**Comment by 5parkp1ug** [comment]
I have a similar problem. When inserting an image, the file gets uploaded to the directory "media" in my app base folder, but it returns error for the uploaded image URL. I have fiddled with MEDIA_ROOT & MEDIA_URL settings but no success. My settings are as below - 

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = 'media/'
FROALA_UPLOAD_PATH = os.path.join(BASE_DIR, 'media')

Here is the log snippet from server --
[14/May/2017 00:26:02] "POST /froala_editor/image_upload/ HTTP/1.1" 200 79 
Not Found: /media/home/abhi/Projects/djApp/media/home_search_image_O0noYRJ.jpg
[14/May/2017 00:26:02] "GET /media/home/abhi/Projects/djApp/media/home_search_image_O0noYRJ.jpg HTTP/1.1" 404 1922

**Comment by Krozark** [comment]
I use this configuration (and it work)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,"public/static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"public/media")

FILE_UPLOAD_PATH = os.path.join(MEDIA_ROOT, 'uploads/')

#FROALA_UPLOAD_PATH = FILE_UPLOAD_PATH
