### ISSUE TITLE
File names not in English become "?????" after uploading

### ISSUE THREAD

**Issue by russian-master** [froala/django-froala-editor#31]
Editors upload files with names in cyrillic: Тест например.docx

These files are saved on server as ???? ????????.docx and can't be opened.

Can we rename them or translify?

**Comment by akki744** [comment]
@russian-master I tried to upload the attached file and it seems to be uploading just fine. The filename is not changed and the file is getting opened. 
Thanks.
[default.zip](https://github.com/froala/django-froala-editor/files/2932069/default.zip)

**Comment by aparna-jha** [comment]
Successfully verified for Django framework. The file gets uploaded finely, the file name is not changed and the file is getting opened as well.
Thanks

![fileupload](https://user-images.githubusercontent.com/48206839/56355902-1a70e980-61f5-11e9-9640-4ded6273cfc5.png)
