### ISSUE TITLE
new release no exist in pypi

### ISSUE THREAD

**Issue by CARocha** [froala/django-froala-editor#33]
Hi, when i install with this command
pip install django-froala-editor
Collecting django-froala-editor
Installing collected packages: django-froala-editor
Successfully installed django-froala-editor-2.0.1

this version install 2.0.1 is incompatible with django 1.10.2, the only way install is dowload
for repository and put in my root folder,

but my question is why is not posible install with pip
pip install django-froala-editor==2.3.5 
Collecting django-froala-editor==2.3.5
  Could not find a version that satisfies the requirement django-froala-editor==2.3.5 (from versions: 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.9.0, 1.2.1, 1.2.2, 1.2.3, 1.2.3.1, 1.2.3.2, 1.2.4, 1.2.4.1, 1.2.4.2, 1.2.5, 1.2.6, 1.2.7, 2.0.0rc3, 2.0.0rc3.post1, 2.0.1)

thank any help

**Comment by davemutton** [comment]
Not sure why it is not in pypi but you could avoid downloading it locally by doing

pip install https://github.com/froala/django-froala-editor/archive/master.zip
