### ISSUE TITLE
django-froala-editor package on Pypi wasn't properly uploaded

### ISSUE THREAD

**Issue by relip** [froala/django-froala-editor#35]
The latest version of django-froala-editor 2.3.5 seems not properly uploaded to Pypi.

https://pypi.python.org/pypi/django-froala-editor shows that 2.3.5 is the latest, and there is README (looks like markdown parsing doesn't work but still), however it isn't available for download from `pip` client. Instead the pip tries to retrieve 2.0.1 which occurs errors on django 1.9 and above.

**Comment by relip** [comment]
I don't know if you guys looked into #27 #33, which are possibly related to this issue; currently closed because they resolved through installing with Github URL. Nevertheless, I think this is still an issue.

**Comment by skyflyer** [comment]
Also related to #37. The package on [pypi](https://pypi.python.org/pypi/django-froala-editor) does **not** include the `README.md` file in the `tar.gz` archive.
