### ISSUE TITLE
django-froala-editor issue with Django 1.10.4

### ISSUE THREAD

**Issue by mapolone** [froala/django-froala-editor#36]
Hello,
I was just trying out Froala (don't have a license at the moment).
Documentation at this time has no references about setting it up on Django 1.10.x (maybe I'm missing something?). In order to get it working, file `lib/python2.7/site-packages/froala_editor/urls.py` should be modified as follows:

```
from django.conf.urls import url
from froala_editor import views

urlpatterns = [
    url(r'^image_upload/$', views.image_upload, name='froala_editor_image_upload'),
    url(r'^file_upload/$', views.file_upload, name='froala_editor_file_upload'),
]
```

patterns() has been [deprecated](https://docs.djangoproject.com/en/1.9/ref/urls/#patterns) since Django 1.8

**Comment by nehemiahjacob** [comment]
Seems the github has the latest changes but it has not moved to PyPi. Can someone release it to there ?

**Comment by stefanneculai** [comment]
@nehemiahjacob it should be fine now. Could you please confirm?
