### ISSUE TITLE
Image format is blob while copying images from Microsoft Word and only work in Chome

### ISSUE THREAD

**Issue by weixiao-huang** [froala/django-froala-editor#39]
While I want to copy an article from Microsoft Word including a lot of images embed in Word, the image can only be uploaded as `blob` in Django's media root like the screenshot below.
![image](https://cloud.githubusercontent.com/assets/8834733/25580468/cd15d306-2eb3-11e7-8032-7f5818a43bfa.png)
And sometimes, this can only upload one image, not all images. Also, this action only works on Chrome, and Safari does not work.

And my version is below
- Django (1.11)
- django-froala-editor (2.5.1)
- djangorestframework (3.6.2)
- mysqlclient (1.3.10)
- olefile (0.44)
- Pillow (4.1.1)
- pip (9.0.1)
- pytz (2017.2)
- setuptools (28.8.0)

The main codes is below

```python
# settings.py
INSTALLED_APPS = [
    ...
    'froala_editor',
    ...
]
...

MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_media"),
)

FROALA_EDITOR_PLUGINS = (
    'align', 'char_counter', 'code_beautifier', 'code_view', 'colors', 'draggable', 'emoticons',
    'entities', 'file', 'font_family', 'font_size', 'fullscreen', 'image_manager', 'image',
    'inline_style',
    'line_breaker', 'link', 'lists', 'paragraph_format', 'paragraph_style', 'quick_insert',
    'quote', 'save', 'table',
    'url', 'video'
)
```

```python
# urls.py
urlpatterns = [
    ...
    url(r'^froala_editor/', include('froala_editor.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

```python
# models.py
...
class Article(models.Model):
    content = FroalaField(options={
        'heightMin': 400
    })
...
```

**Comment by stefanneculai** [comment]
This should be working fine in the latest editor version.
