### ISSUE TITLE
Froala not working in Django admin's inlines

### ISSUE THREAD

**Issue by Fanarim** [froala/django-froala-editor#40]
In Django admin, using FroalaField/FroalaWidget in inline model breaks the editor. No Froala buttons can be pressed, characters are not counted, placeholder doesn't disappear, no content is saved after submission.
This might be a general problem with formsets.

**Comment by Jufik** [comment]
Same in here, no JS error or any thing.
My guess is that it's hanging around initialization.

The issue happens when you try to add a new element in the inline.
If the form is already initialized -in my case using a min_num=1- I got it working.

**Comment by Wtower** [comment]
Great editor, but unfortunately same too me. Subscribing.

**Comment by blablacio** [comment]
You could override your change_form.html with something along these lines:
```
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script type="text/javascript">
(function($) {
    $(document).on('formset:added', function(event, $row, formsetName) {
        $row.find('textarea').each(function() {
            $(this).prev().remove();
            jQuery(this).froalaEditor();
        });
    });
})(django.jQuery);
</script>
{% endblock %}
```

**Comment by kentuck13** [comment]
I Caught 'admin/change_form.html' and add code as say **blablacio**. Now everywhere always work. THX!!!

**Comment by xtranophilist** [comment]
Thank you @blablacio .
