### ISSUE TITLE
Froala editor doesn't shows bulletpoints

### ISSUE THREAD

**Issue by mikolajkosmal** [froala/django-froala-editor#46]

**Comment by stefanneculai** [comment]
@mikolajkosmal most likely you have some other CSS on the page which conflicts with the editor.

**Comment by thegumbyman** [comment]
I found this too, when using the widget in an admin form.

The built-in django admin css is resetting list style, see:
https://github.com/django/django/blob/2.0.5/django/contrib/admin/static/admin/css/forms.css#L148

**Comment by affan10** [comment]
So what was the fix for this, if anyone got to do it?

**Comment by affan10** [comment]
For anybody who comes here looking for a fix:

1. Create a change_form.html file in project_name > templates > admin directory.
2. Paste this in the file and everything should work as expected:
```
{% extends "admin/change_form.html" %}
{% load i18n static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <style>
        form .aligned ul li {
            list-style: inherit;
        }
    </style>
{% endblock %}
```

**Comment by affan10** [comment]
Anyone who comes here looking for a fix:

1. Create change_form.html inside your_project_name > templates > admin directory.
2. Paste the following and all should work as expected:
`
{% extends "admin/change_form.html" %}
{% load i18n static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <style>
        form .aligned ul li {
            list-style: inherit;
        }

        form .aligned ul {
            margin-left: 5%;
            padding-left: 10px;
        }
    </style>
{% endblock %}
`
