### ISSUE TITLE
Reinitialized froala in admin inlines does not accept original settings

### ISSUE THREAD

**Issue by ron8mcr** [froala/django-froala-editor#53]
Fixes in commit 44534024f7973d54357fe95a58f8d57378a86f0c does not handle custom settings that were added for editor.

Also this fix tries to reinitialize all text areas in added inline, even that does not have froala defined

**Comment by shashankaccolite** [comment]
Hi @stefan, froala editor is working fine in admin inlines on my machine. This issue is not reproducible.
Please review it.
Thanks
