### ISSUE TITLE
render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by rafagarciac** [froala/django-froala-editor#55]
I had a problem when I trying to implement the Froala Editor in my DJango Application... I leave here the error Stack. If you know what's the problem please, tell me know. 👍 

![image](https://user-images.githubusercontent.com/32666357/42395023-854e998e-815c-11e8-87b8-dfe39830e51d.png)
![image](https://user-images.githubusercontent.com/32666357/42395035-90eae8a6-815c-11e8-8e5d-df86dba55196.png)

I followed all installed instruction strictly. I don't know what happen 
Version of Froala Editor: **v2.8.4**

**Comment by zvolsky** [comment]
I don't use Froala. In my case with dj21rc1 problem was django-ajax-selects, where render() has no renderer= param.
So maybe froala_editor/widgets.py needs render(......, renderer=None)

**Comment by 0x00fi** [comment]
My solution : 
Navigate to django/forms/boundfields.py
And remove line 93 (renderer=self.form.renderer).

Ugly solution...

**Comment by xtranophilist** [comment]
Thanks guys, this should be fixed now.
