### ISSUE TITLE
Cannot find reference 'S3' in '__init__.py'

### ISSUE THREAD

**Issue by adnanrafique** [froala/django-froala-editor#57]
I am using django-froala-editor to generate a signature and policy and these policy and signature both will be returned to my Front end which is build in Angular 5.

I am following [this](https://www.froala.com/wysiwyg-editor/docs/sdks/python/image-s3-upload) link to make it work in django but I am getting syntax error 

> Cannot Find reference 'S3' in '__init__.py'

On the following line of code.
`from floara-editor import S3`

![screenshot_27](https://user-images.githubusercontent.com/20041254/45406678-a380da80-b680-11e8-9179-a4007ae9df79.png)

Please help.

**Comment by stefanneculai** [comment]
Please make sure that you include the Python SDK in your app: https://www.froala.com/wysiwyg-editor/docs/sdks/python.
