### ISSUE TITLE
Cannot integrate froala in Django Admin

### ISSUE THREAD

**Issue by toufikswar** [froala/django-froala-editor#58]
Hello all,

I am trying to integrate Froala editor within django admin. I understood from the doc that the process is pretty straight forward. 
I followed the getting started and usage part of the documentation here https://github.com/froala/django-froala-editor. 

I created in my **model.py** : 

```
from froala_editor.fields import FroalaField
from django.db import models

class Service(models.Model):
    message = FroalaField()
```
When I log in the admin interface, the field shows as a textarea.

Do you have any idea why ? Am I doing something wrong?

Many thanks,

**Comment by BronzeCrab** [comment]
Has exactly the same issue, looking for help.

**Comment by BronzeCrab** [comment]
I figured it out. There is a typo on [this page](https://www.froala.com/wysiwyg-editor/docs/framework-plugins/django), `OR` should be `AND`. So you just need to:

1. Add `froala_editor` to `INSTALLED_APPS` in settings.py.

2. Add the following line to `urlpatterns` in your application's `urls.py`:

  ```url(r'^froala_editor/', include('froala_editor.urls')),
```

**Comment by mrGain** [comment]
Now I am also getting the same issue. any idea how to fix it??
