### ISSUE TITLE
Something went wrong (403, csrf token is null) when trying to upload an image.

### ISSUE THREAD

**Issue by prathyush-bsc** [froala/django-froala-editor#61]
I am using django forms with **FroalaEditor from froala_editor.widgets**. The image uploading works fine when I upload it in my local server. But when I push the code to a Ec2 server instance and try uploading an image using the froala field, an Error pops, saying "Something went wrong please try again"

Its a 403 error.
When I looked in the network, the  cookie in the request headers is generated 
Cookie:csrftoken=*********************************************************************

but the csrfmiddlewaretoken in the formData is NULL.

Again it works fine when I try it in my local. When I host it on server, its causing this issue. Please help

**Comment by stefanneculai** [comment]
Duplicate of #52 .
