### ISSUE TITLE
Admin inlines. Adding inline appends froala to all text fields

### ISSUE THREAD

**Issue by Mykyta-Chernenko** [froala/django-froala-editor#63]
https://github.com/froala/django-froala-editor/issues/40

Solution of this issue is wrong. 
It both appends froala to all text fields and not only to froala fields
and doesn't add any options

**Comment by xtranophilist** [comment]
Hi @marakaci, thanks. Yes, this is an open issue and duplicate of #53.
We will work on it. If you already have a solution, please send us a PR.
