### ISSUE TITLE
froala in django admin not working well

### ISSUE THREAD

**Issue by LoongGx** [froala/django-froala-editor#70]
im new to django, the poster field is out of control, is this situation normal in django admin?

![issue1](https://user-images.githubusercontent.com/49709067/59314490-328e5200-8ce8-11e9-91bd-951ec6366a37.png)

**Comment by zachtaylor21** [comment]
I've been having that problem too. Would love a fix for this.

**Comment by LoongGx** [comment]
> I've been having that problem too. Would love a fix for this.

Hi, I found the problem happen when i use foreign key in django admin, is that same for you?

**Comment by zachtaylor21** [comment]
For me it happens just on a normal TextField, using the FroalaEditor widget

**Comment by ron8mcr** [comment]
I found that problem is with [this CSS rule](
https://github.com/froala/django-froala-editor/blob/009bf97e0b6ec4d9efa821232cc68a0bb23c0ac7/froala_editor/static/froala_editor/css/froala-django.css#L15) that breaks Django's form styles, and reverted back to `
`django-froala-editor==2.9.1`

**Comment by LoongGx** [comment]
This issue has been resolved

**Comment by StevenMapes** [comment]
Why has this been closed when the issue is still there?
