### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by davemutton** [froala/django-froala-editor#8]
When uploading images the uploaded image is saved to uploads/froala_editor/images but the image does not appear in the editor or the html. This happens in forms and admin.

Steps taken to install:
pip install django-froala-editor
url(r'^froala_editor/', include('froala_editor.urls')), added to urlpatterns
Form.py has charfield with the widget set to Froala (widget=FroalaEditor)

**Comment by davemutton** [comment]
By looking at the console while trying to upload an image (of myself) I can see that it returns the url http://10.88.8.98:8081/admin/wiki/page/add/uploads/froala_editor/images/Mutton%20Dave.jpg/ 

when it should be returning 
http://10.88.8.98:8081/uploads/froala_editor/images/Mutton%20Dave.jpg/

**Comment by stefanneculai** [comment]
It looks like you should set `FROALA_UPLOAD_PATH` to `/`. @xtranophilist is that right?

**Comment by sakisbl** [comment]
Hi all, 

I encounter the same problem. By looking at the console while trying to upload an image the following URL is returned:

/admin/pezapp/post/23/uploads/froala_editor/images/054331_WL7t5sE.jpg

Also, when I set FROALA_UPLOAD_PATH to / , I encounter a 400 error.

Do you have any idea what is going on or any hint to fix this problem?

Thank you.

**Comment by davemutton** [comment]
I fixed this for myself by going to the views.py of froala_editor and changing line 22 from 
link = default_storage.url(path)
to
link = "/media/"+default_storage.url(path)

while I was there I also added 

def file_upload(request):
        if 'file' in request.FILES:
            the_file = request.FILES['file']
            upload_to = getattr(settings, 'FROALA_UPLOAD_PATH', 'uploads/froala_editor/files/')
            path = default_storage.save(os.path.join(upload_to, the_file.name), the_file)
            link = "/media/"+default_storage.url(path)
            return HttpResponse(json.dumps({'link': link}), content_type="application/json")

to get drag and drop file uploading working correctly.

**Comment by sakisbl** [comment]
Thank you Dave.

I tried your solution and it works as expected :+1:

**Comment by davemutton** [comment]
Excellent

**Comment by stefanneculai** [comment]
@davemutton we've updated the master version like you suggested. :+1:

**Comment by xtranophilist** [comment]
@davemutton @sakisbl 
Make sure you have MEDIA_URL configured in your project. Looks like it needs to be set as '/media/'.
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MEDIA_URL
